secretics="jfosnofsnodinfosdnfos"

AWS_SECRET_ACCESS_KEY = "0v5gVmLut2RoZYNWv7K+99bViqoB6RPeqEw4lFSo"
AWS_ACCESS_KEY_ID = "AKIAU5LH6CMST4NAYMXW"

"-----BEGIN DSA"


parol="1939njfjslxnbn2"
AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY